import test from 'node:test';import assert from 'node:assert/strict';import {analyze,parseMint,parsePairs,PROGRAMS} from '../server/analyze.mjs';import {MAINNET_GENESIS} from '../server/rpc.mjs';
const mint='So11111111111111111111111111111111111111112';
const valid=()=>({context:{slot:123},value:{owner:PROGRAMS[0],data:{parsed:{type:'mint',info:{isInitialized:true,decimals:9,supply:'123456789',mintAuthority:null,freezeAuthority:null}}}}});
test('invalid inputs cannot trigger source requests',async()=>{let calls=0;await assert.rejects(analyze('https://evil.test',{rpc:()=>calls++,fetcher:()=>calls++}),/valid Solana/);assert.equal(calls,0);});
test('wrong program, missing account and malformed authority fail closed',()=>{assert.throws(()=>parseMint({value:null}));const a=valid();a.value.owner='x';assert.throws(()=>parseMint(a));const b=valid();b.value.data.parsed.info.mintAuthority='bad';assert.throws(()=>parseMint(b));assert.equal(parseMint(valid()).decimals,9);});
test('markets require Solana and exact base mint; missing values are not zero',()=>{const pair={chainId:'solana',pairAddress:mint,baseToken:{address:mint}};const r=parsePairs([pair,{...pair,chainId:'eth'},{...pair,baseToken:{address:'wrong'}}],mint);assert.equal(r.length,1);assert.equal(r[0].liquidity,null);assert.equal(r[0].priceUsd,null);});
test('partial results keep market evidence without inventing chain data',async()=>{const r=await analyze(mint,{rpc:async()=>{throw Error('RPC unavailable');},fetcher:async()=>({ok:true,text:async()=>'[]'})});assert.equal(r.status,'partial');assert.equal(r.chain,null);assert.equal(r.sources[0].status,'unavailable');assert.equal(r.sources[1].status,'observed');assert.equal(r.checksum.length,64);});
test('complete source reads preserve finalized slot and exact integer supply',async()=>{const r=await analyze(mint,{rpc:async method=>method==='getGenesisHash'?MAINNET_GENESIS:valid(),fetcher:async()=>({ok:true,text:async()=>'[]'})});assert.equal(r.status,'complete');assert.equal(r.chain.slot,123);assert.equal(r.chain.supply,'123456789');});
test('wrong network never becomes mint evidence',async()=>{let calls=0;const r=await analyze(mint,{rpc:async()=>{calls++;return 'devnet'},fetcher:async()=>({ok:false})});assert.equal(calls,1);assert.equal(r.chain,null);assert.equal(r.sources[0].status,'unavailable');});
